title: ZeroShotBot
default_lang: en
author:
  name: ZeroShotBot
  email: info@zeroshotbot.com
taxonomies:
  - category
  - tag
  - month
metadata:
  keywords: 'virtual assistant, ai, artificial intelligence, bot'
  description: 'Leverage a next-gen Conversational AI Chatbot to deliver an advanced, omni- channel customer experience. Visit our website to learn more.'
summary:
  enabled: true
  format: short
  size: 250
  delimiter: '==='
redirects: null
routes: null
blog:
  route: ''
