title: ZeroShotBot
default_lang: en
author:
  name: ZeroShotBot
  email: info@zeroshotbot.com
taxonomies:
  - category
  - tag
  - month
metadata:
  keywords: 'virtual assistant, ai, artificial intelligence, bot'
  description: ''
summary:
  enabled: true
  format: short
  size: 250
  delimiter: '==='
redirects: null
routes: null
blog:
  route: ''
